export default {
  MAX_PLAYERS: 6,
  MAX_HEARTBEAT_INTERVAL: 3000,
  CHECK_CONNECTION_INTERVAL: 500,
  SEND_STATE_INTERVAL: 250,
  GAME_STATE: {
    PLAYERS_CONNECT: 0,
    VOTE_JOURNEY: 1,
    ON_JOURNEY: 2,
    STATS_REVIEW: 3,
    VOTE_SPY: 4,
    JOURNEY_REVIEW: 5,
    GAME_REVIEW: 6,
  }
};
