export default {
  MAX_PLAYERS: 6,
  MAX_HEARTBEAT_INTERVAL: 3000,
  CHECK_CONNECTION_INTERVAL: 500,
  SEND_STATE_INTERVAL: 250,
  GAME_STATE: {
    PLAYERS_CONNECT: 0,
    CHOOSE_ROLE: 1,
    VOTE_JOURNEY: 2,
    ON_JOURNEY: 3,
    STATS_REVIEW: 4,
    VOTE_SPY: 5,
    JOURNEY_REVIEW: 6,
    GAME_REVIEW: 7,
  }
};
